### ISSUE TITLE
 Failed to establish a new connection: [Errno 61] Connection refused'

### ISSUE THREAD

**Issue by Jason57Fr** [allenporter/pyrainbird#21]
Hello Guys,

i try to implement the python script in my place and i got the following error when i test it : 

DEBUG:pyrainbird:Sending {"id":1591814318,"jsonrpc":"2.0","method":"tunnelSip","params":{"data":"05","length":1}} to x.x.x.135, 3. try.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1):  x.x.x.135:80
WARNING:pyrainbird:Unable to connect: HTTPConnectionPool(host='x.x.x.135.135', port=80): Max retries exceeded with url: /stick (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1090cda10>: Failed to establish a new connection: [Errno 61] Connection refused',))
WARNING:pyrainbird:Response not returned.
DEBUG:pyrainbird:Response from line: None
WARNING:pyrainbird:Empty response from controller

here the code i use : 

# Test for controller
from pyrainbird import RainbirdController
import time
import logging

logging.basicConfig(filename='pypython.log',level=logging.DEBUG)

_LOGGER = logging.getLogger(__name__)
_LOGGER .setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
_LOGGER.addHandler(ch)

controller = RainbirdController("X.X.X.135","XXXXXX")
controller.get_serial_number()

Any idea?

**Comment by Jason57Fr** [comment]
Sorry , found out it was a FW issue

**Comment by holoduke** [comment]
> Sorry , found out it was a FW issue

Which firmware were you using. did you manage to fix it? and how.
I am using 1.63. having the same issue. No idea how to update the firmware
