### ISSUE TITLE
Conflicting setup requirement with standard library for Python 3.7 / 3.8

### ISSUE THREAD

**Issue by MartinHjelmare** [allenporter/pyrainbird#23]
- This library supports an integration in Home Assistant.
- One or more of the requirements of this library (see below) conflicts with one or more standard library modules for Python 3.7 and/or 3.8.
- To avoid issues it would be good if this library would remove these conflicting requirements from your library setup requirements or use a condition to only install the requirements when using a lower Python version.
- If a `setup.py` file is used it means updating the `install_requires` list and removing or updating the conflicting requirements.
  - See this blog for how to use a condition in `install_requires`: https://hynek.me/articles/conditional-python-dependencies/
- Found conflicts:
  - `datetime`

Thanks for your support of Home Assistant!

**Comment by allenporter** [comment]
Will be fixed in Home Assistant in a future release that addresses this and other problems.
