### ISSUE TITLE
Support for Rainbird NCC-WF Wifi cartridge?

### ISSUE THREAD

**Issue by robby-d** [allenporter/pyrainbird#28]
As the topic says, wondering if this library supports the Rainbird NCC-WF Wifi cartridge (see https://www.rainbird.com/sites/default/files/media/documents/2018-02/ts_IQ-NCC_D40032EO.pdf). This appears similar to the LNK WiFi module, but is meant towards larger installations. I don't have one yet so I cannot test it unfortunately. And, I can't find any API specs on Rainbird's site. (I'm am guessing the API was reverse engineered?)

**Comment by allenporter** [comment]
Yeah, I am not aware of any documentation and it seems like this was reverse engineered. I am going to close this issue, and I think makes sense to re-open when someone has the device and is planning to add support for this.
