### ISSUE TITLE
Start Program

### ISSUE THREAD

**Issue by laserir** [allenporter/pyrainbird#29]
Hi! Is it also possible to start a program (e.g. PRG A) with your piece of code? I saw there seems to be a function defined, but as a total newbie regarding this, I cannot figure out the command. :(

**Comment by allenporter** [comment]
Hi, there is an example of how to use this library in the `README` on the front page. The library is fairly low level and requires python knowledge, so you may want to integrate with a "higher level" system such as home assistant for controlling the device -- much more powerful and user friendly. I'm going to close this.
