### ISSUE TITLE
Setting for Rain Sensor (Bypass/Active)

### ISSUE THREAD

**Issue by lukicsl** [allenporter/pyrainbird#3]
Would it be possible to implement setting Rain Sensor setting, e.g. Active/Bypass
btw. Where did you get the API definition from. I was not able to find one?

**Comment by ionred** [comment]
@jbarrancos Curious as well on the API definition -- how did you go about getting that information?

**Comment by jbarrancos** [comment]
Hmm not seeing it as part of the default API spec. This would take some nettracing or checking the code. Both will take me some time which i dont’t have right now. I’ll see if i can get some time to analyze the traffic.

**Comment by jbarrancos** [comment]
The API is clear text in the android code. Additionally rest is by tracing / decrypting the traffic using a stub service.

**Comment by lukicsl** [comment]
Controlling this setting by home automation would make it possible, by actually measuring rain (mm/m2), to precisely override the defined schedule. The sensor HW is a crap, I will remove it.
