### ISSUE TITLE
'encoding' argument removed in json.loads in Python 3.9

### ISSUE THREAD

**Issue by srozb** [allenporter/pyrainbird#33]
According to [Python 3.9 json module documentation](https://docs.python.org/3/library/json.html#json.loads), 'encoding' argument is removed.

But still used [here](https://github.com/jbarrancos/pyrainbird/blob/d9fc7b4a1c845277ef6f0b4501e8053ef0556453/pyrainbird/resources/__init__.py#L7).

This unfortunately renders the library unusable under 3.9 and Home Assistant 2021.07.

**Comment by frenck** [comment]
PR in this repo: #32

@jbarrancos Is that something you can help out with?

**Comment by peternijssen** [comment]
@jbarrancos Any chance you can release this as 0.4.3 so we can update the dependency in HA? I guess this issue can be closed afterwards.

Thanks!

**Comment by jbarrancos** [comment]
Build latest
