### ISSUE TITLE
How to connect to the Rain Bird LNK-WIFI or application?

### ISSUE THREAD

**Issue by dommarion** [allenporter/pyrainbird#35]
Hello jbarrancos,
I have read all your development, and congrats !
I would like to adapt it to the eedomus box, and to start with I would need some information how to initially connect to the Rain Bird LNK-WIFI or application?
If you can explain and help me, I will apply the rest of the package to the eedomus box.
Thanks
Regards,
dommarion

**Comment by allenporter** [comment]
Hi, this is a lower level python library -- with some examples in the README. You may want to go with a higher level way to integrate like home assistant if you are looking for an easier way to integrate with raindbird, rather than using this low level library.
