### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [allenporter/pyrainbird#41]
Could you please tag the source? This allows distributions to get the complete source from GitHub.

Thanks

Related #38

**Comment by allenporter** [comment]
@fabaff Hi i'm not sure what "tag the source" exactly means, but i plan to move this to use a standard pypi publishing via github actions and package with setup.cfg.  I think that should be sufficient but let me know if there is something more specific that is needed.

**Comment by allenporter** [comment]
I see what you mean, 0.5.0 was not tagged in github. I've fixed this with 0.6.0
