### ISSUE TITLE
Support for LNK2 WiFi

### ISSUE THREAD

**Issue by J0EK3R** [allenporter/pyrainbird#42]
Hello and many thanks for this project!

I took this project as base for an implementation for the **[FHEM](https://fhem.de) home automation system** written in **Perl**:
**[fhem-rainbird](https://github.com/J0EK3R/fhem-rainbird)**

Now Rain Bird has released a new WiFi stick **[Rain Bird LNK2 WiFi](https://www.rainbird.com/products/lnk2-enhanced-control)**.

Sadly my implementation can't communicate to the device using "tunnelSip" as methode.
The responses for all commands using "tunnelSip" always are:
_{"error":{"code":-32602,"message":"Invalid parameters"},"id":43,"jsonrpc":"2.0","result":{"text":"NoResult"}}_
Communication using the methodes "getNetworkStatus", "getSettings", "getWifiParams" is working.

Now I'm asking myself if my implementation is faulty or if the LNK2 stick has a different structure of the commands!?

Did someone manage to communicate to a LNK2 WiFi with pyrainbird?

**Comment by emeins** [comment]
I tested the irrigation test script with LNK2 successfully.
Please find the log entries below:
![image](https://user-images.githubusercontent.com/17033201/168999594-7310e01b-aa76-47eb-9397-31afbcdde795.png)

**Comment by J0EK3R** [comment]
Thank you a lot for your quick response!
