### ISSUE TITLE
Incorrect Zone Reported

### ISSUE THREAD

**Issue by CarsonF** [allenporter/pyrainbird#5]
Hey thanks for your work on this, you seem to be the only one 👍

The zones are not getting parsed correctly. I'm wondering if you came up with the algorithm yourself or found it their source code. I'm guessing you came up with it yourself and you don't have more than 4 zones 😉

Zone | Response | Parsed
----- | ---------- | -------
Off | BF0000000000 | 0
1 | BF0001000000 | 1
2 | BF0002000000 | 2
3 | BF0004000000 | 3
4 | BF0008000000 | 4
5 | BF0010000000 | **4**
6 | BF0020000000 | **5**
7 | BF0040000000 | **6**
8 | BF0080000000 | **7**
9 | BF0000010000 | **0**

Their response sequence is very strange, and I haven't figured out a "nice" way to parse it. The 9th zones really throws me for a loop. It makes me wonder if the response needs to be split into chunks of two and then flipped? 🤔 I also wonder if it's different for different controllers? Mine's a ESP-Me.

----

I've also been trying to do some reverse engineering myself. I've tried decompiling their app and sniffing their traffic. I couldn't find much plain text in the app code. And the traffic was encrypted. I didn't try very hard to decrypt it, as it was the end of the day. I spent most of the day trying to get a MITM proxy set up. I did get it working but then the app was trying to communicate with their cloud via a websocket and the connection would not establish - it just hung and then failed. Finally I switched over to Wireshark without the proxy and was able to see traffic.

Any tips would be very helpful 😁

**Comment by tfoote** [comment]
@CarsonF Please take a look at #6 for a possible fix.
