### ISSUE TITLE
Rainbird API

### ISSUE THREAD

**Issue by horendus** [allenporter/pyrainbird#8]
Hi, I know this isn't an "issue" as such but I was wondering where you managed to get the Rainbird API from? So far I have not been able to get a response out of them over the phone. Im looking at integrating it with a 3rd party system however it does not run Python.

I have done some tests using your module and it works as expected, however reverse engineering an API from your module is more difficult that having an API document.

Thanks!

**Comment by ionred** [comment]
If I recall correctly this was reverse engineered by unzipping the APK.

**Comment by jbarrancos** [comment]
Correct and by creating a stub service to control and gain more insights
